### ISSUE TITLE
Current azure-mgmt-containerregistry lacks QuickBuildRequest

### ISSUE THREAD

**Issue by Coobik** [Azure/acr#140]
Hi all,

This example is outdated.
In the current azure-mgmt-containerregistry version 1.16.0 that is available on maven central, there is no QuickBuildRequest and Registries interface does not have queueBuildAsync method.

Can anybody point me to the new solution? I was unable to find any guide/description how to use  Azure container registry APIs for java or node.js. Just nothing.
How can I connect and build docker image on the azure container registry? Are there any working examples for java or javascript? Maybe REST API? Meaningful parameter description?
thanks!

**Comment by northtyphoon** [comment]
@Coobik, please get the java sdk from https://search.maven.org/search?q=g:com.microsoft.azure.containerregistry.v2018_09_01

We have updated the Java example in https://github.com/Azure/acr/tree/master/samples/java/task 

We also publish the REST API spec in https://docs.microsoft.com/en-us/rest/api/containerregistry/registries%20(tasks)

**Comment by Coobik** [comment]
@northtyphoon hi! thanks for your help. 
what about the artifact in maven central https://mvnrepository.com/artifact/com.microsoft.azure/azure-mgmt-containerregistry/1.16.0 it's release date is Sep 25, 2018 
why does it lack the classes? are there any plans to make them available in the official artifacts?

I've seen the REST API spec, it's not so clear. There are no examples of the possible values. No use cases described.
Looking at the REST spec, I've tried to use node.js SDK:

const runRequest: models.DockerBuildRequest = {
            argumentsProperty: [],
            dockerFilePath: "Dockerfile-python-slim",
            imageNames: ["MY_REGISTRY.azurecr.io/python-slim:v1"],
            isPushEnabled: true,
            platform: {
                architecture: "amd64",
                os: "Linux",
            },
            sourceLocation: "https://github.com/Coobik/future",
            type: "DockerBuildRequest",
        };
await client.registries.scheduleRun(resourceGroupName, registryName, runRequest);

In the activity log of container registry on azure portal, i see ScheduleRun is Succeeded, but no docker image appeared in Repositories list. Do you know anything about that?

I'm in a need of sample possible values to put into requests, i couldn't find them anywhere. All i can do is guessing.

One more question.. How can I pass a Dockerfile and other content with docker build request? Example shows that I need to host Dockerfile on a github repo. Are there any other way to store Dockerfile and other files i want to put into docker image? Are there any examples showcasing other ways?

thanks for your help!

**Comment by Coobik** [comment]
update: if i remove MY_REGISTRY.azurecr.io from image name, the image appears in repositories list on azure portal

**Comment by northtyphoon** [comment]
> what about the artifact in maven central https://mvnrepository.com/artifact/com.microsoft.azure/azure-mgmt-containerregistry/1.16.0 it's release date is Sep 25, 2018
why does it lack the classes? are there any plans to make them available in the official artifacts?

Currently Azure provides two Java SDKs both provide Fluent API. azure-mgmt-containerregistry is hand-crafted and provide some additional fine-tuned interfaces to further optimize the development experience. However its release is usually several weeks behind service update because of the additional optimization step. It will probably be updated with the new capability in the next two weeks or so. The other SDK is automatically generated from the API Spec which is also supported by us.

> In the activity log of container registry on azure portal, i see ScheduleRun is Succeeded, but no docker image appeared in Repositories list. Do you know anything about that?

ScheduleRun is to queue the build and return a run id. Later, you can poll the run status from https://docs.microsoft.com/en-us/rest/api/containerregistry/runs/runs_get. You can then call https://docs.microsoft.com/en-us/rest/api/containerregistry/runs/runs_getlogsasurl to get the
full build log. Check the Java example I shared above.

> Are there any other way to store Dockerfile and other files i want to put into docker image? Are there any examples showcasing other ways?

You can pack the files to tar.gz file and upload to the storage blob. Here is an example used in vscode docker extension.
https://github.com/AzureCR/vscode-docker/blob/dev/commands/azureCommands/acr-build.ts#L71

> update: if i remove MY_REGISTRY.azurecr.io from image name, the image appears in repositories list on azure portal

If you prefix the image tag with `MY_REGISTRY.azurecr.io`, it tells the builder to push the image to the registry `MY_REGISTRY`. It's the same behavior as `docker build` and `docker push`. If you don't prefix the tag with registry name, the builder will automatically push to the registry that you used to schedule the run.

**Comment by ehotinger** [comment]
@northtyphoon @Coobik can this be closed?

**Comment by northtyphoon** [comment]
@Coobik, awesome, thanks for confirm. please let us know if you have any feedback.
