### ISSUE TITLE
build step could not treat the context path correctly.

### ISSUE THREAD

**Issue by adashen** [Azure/acr#160]
**BUG REPORT**:

**What happened?**:
I specify the build context path in the build step in the .yaml file like
/workspace/modules/csharpModule/Dockerfile.arm32v7
However build failed and the error is 
/workspace/modules/csharpModule/workspace/modules/csharpModule/Dockerfile.arm32v7, error: open /workspace/modules/csharpModule/workspace/modules/csharpModule/Dockerfile.arm32v7: no such file or directory
Error: failed to run step ID: acb_step_0: failed to scan dependencies: exit status 1

But if I use cmd step and specify the step like
cmd: docker build ....
it works

**What did you expect to happen?**:
context path should work in build step.

**Comment by northtyphoon** [comment]
@adashen, can you copy/paste the .yaml file here or email to us?

**Comment by northtyphoon** [comment]
@rosanch, can you follow up with @adashen ?

**Comment by ehotinger** [comment]
@adashen can you help provide additional information on your bug reports?

**Comment by ehotinger** [comment]
@adashen should be fixed now, but we won't be able to deploy until January since things are on freeze right now. You can continue using the workaround with `docker build` explicitly as `cmd:` -- I would recommend not hardcoding paths like `/workspace/...` since `/workspace` could change at any time.
