### ISSUE TITLE
acr build - Information messages sent to stderr

### ISSUE THREAD

**Issue by xenalite** [Azure/acr#162]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

**What happened?**:
I queue ACR image builds by calling `az` from PowerShell.

I want to fail the VSTS build if `az acr build` pushes any logs into stderr.
My builds started to fail even if ACR build was successful and no Error messages were shown in the logs.
So I redirected stderr stream into a file.
```
$buildJob = Start-Job -ScriptBlock { & az acr build --registry $using:AzureContainerRegistryName --file $using:dockerfileName --image $using:imageName --os $using:imageOs $using:imageDir 2>"D:\$(New-Guid).log" }
```

Turns out `az acr build` sends perfectly ordinary messages into the error stream:
```
az.cmd : WARNING: Packing source code into tar to upload...
At line:1 char:2
+  & az acr build --registry $using:AzureContainerRegistryName --file $ ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Packin...ar to upload...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
WARNING: Uploading archived source code from 
'C:\Users\SVEAZR~1\AppData\Local\Temp\build_archive_4721948b9beb46ff949f46353cacb5d3.tar.gz'...


WARNING: Sending context (4.913 MiB) to registry: ixsamldem20cr01dev...


WARNING: Queued a build with ID: cb5

WARNING: Waiting for agent...


```

**What did you expect to happen?**:
I don't believe any of these should be warnings. They are part of normal operation of `az acr build` command when uploading a directory to ACR. A successful build command should produce nothing in the stderr stream.

**Environment (if applicable to the issue)**:
 - Azure CLI/Powershell/SDK version: 2.0.51
 - OS version: Windows Server 2016

**Comment by ehotinger** [comment]
@yugangw-msft or @tjprescott  does `logger.warning` go to `stderr` by default? If so, why? Warnings shouldn't be treated as errors. Should we switch all of the logging for ACR related to streaming events to `print` and not use the logger?

**Comment by northtyphoon** [comment]
In general warnings go to stderr. 

Interestingly CLI guideline suggests below.

```Log to logger.error() or logger.warning() for user messages; do not use the print() function```

https://github.com/Azure/azure-cli/blob/de2fd2ebb4bfa765698783bedd15053be27469ee/doc/command_guidelines.md

**Comment by ehotinger** [comment]
@xenalite so after quite a bit of discussion we've decided not to change this for now. We want to reserve the ability to print warnings on stderr. Don't fail your CI just because messages appear on stderr. Just check the exit code for a non-zero exit code instead. These specific messages could be improved slightly to be put on stdout, but in order to support `--no-logs` we've put them on `logger.warning` as a way to parse `stdout` and `stderr` differently for other scenarios. We also have some deprecation warnings already which need to stay, i.e. `{{.Build.ID}}` is deprecated in favor of `{{.Run.ID}}`. Let me know if that makes sense.

/cc @djyou as FYI.

**Comment by e-jr** [comment]
Although this thread has been closed some time ago I'd like to add one scenario.
We're using Octopus Deploy as deployment server which uploads images. It checks the logs for warnings and displays a warning icon in case some where found.
![image](https://user-images.githubusercontent.com/124878039/221781180-84d10d46-2603-447c-802d-4f1f072d4e0c.png)
All successful uploads are now displayed with a warning icon which indicates it worked but there's something to fix. This behavior can't be changed. Since those logs are part of normal operation they should not be printend as warnings.
