### ISSUE TITLE
Calling /oauth2/exchange with wrong method produces 404

### ISSUE THREAD

**Issue by yevster** [Azure/acr#166]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened?**:
Invoked the following PowerShell code snippet

```PowerShell
Invoke-RestMethod -Method Get `
                -Body $requestBody `
                -Uri $exchangeUri
```
where `$exchangeUri` is  https://feedbackcr.azurecr.io/oauth2/exchange and requestBody is a hashmap of fields.

This resulted in a 404 error, making me double- and triple-check the URI instead of casting suspicion on the HTTP method.

**What did you expect to happen?**:
Per the [HTTP Status Codes](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) spec, attempting to call an illegal method on a URI should result in a 405 status code. 

**How do you reproduce it (as minimally and precisely as possible)?**:
(See description)
**Anything else we need to know?**:

**Comment by yuwaMSFT2** [comment]
Thanks @yevster for the suggestion.
These endpoints are more auth APIs, instead of operations on REST resources. So they don't exactly follow RESTful API.

The "/exchange" EP only supports POST method:
https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#calling-post-oauth2exchange-to-get-an-acr-refresh-token

For the more standard oauth2 endpoint "/token", POST is supported to obtain the access token:
https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#calling-post-oauth2token-to-get-an-acr-access-token

Also in order to be compatible with docker client, we also support GET on "/token" EP:
https://docs.docker.com/registry/spec/auth/jwt/#getting-a-bearer-token

We tried the auth endpoints of several other services (docker hub, Microsoft AAD). If you send request with unsupported method type, you will get 404. 

Although I understand that it might be desirable to return 405, it would be low priority and customers should not have confusion to use them. Please let us know if you have other suggestions. Thanks!

**Comment by yuwaMSFT2** [comment]
@yevster if the grant_type is access_token, you do not need to provide refresh token. It may means that the access_token you provided doesn't have permission on the registry.

If you think you provided the right permission to the user, and still get access problem, you can send the details to our support email acrsup@microsoft.com so that we can help to investigate:
a. Registry name
b. The exact command that fails
c. The user name that you used to retrieve the token
d. the approximate time frame

Thanks!

**Comment by yuwaMSFT2** [comment]
@yevster have you tried it again? Please send us details in email if you need additional help.

**Comment by yevster** [comment]
I think permissions are the culprit. This was running in Azure Automation with their Service Principal, which does not seem to have API access by default.
