### ISSUE TITLE
Support for quarantine flow in API v2

### ISSUE THREAD

**Issue by mgrabarz** [Azure/acr#210]
**FEATURE REQUEST/GUIDANCE**:

**What happened?**:
I am just configuring my ACR with quarantine flow, following your [article](https://github.com/Azure/acr/tree/master/docs/preview/quarantine) in this repo.  
Article assumes quarantine flag for image is disabled via PATCH v1/{{image}}/_manifests/{{digest}}, however this only applies to classic (v1 API enabled) ACRs. How do I reset quarantine with v2?

**What did you expect to happen?**:
It would be great if you updated quarantine doc or provide any description for the proces.
At the moment patch to v2/{image}/manifests/{digest} returns following:
`{
    "errors": [
        {
            "code": "IMAGE_QUARANTINED",
            "message": "The image is quarantined.",
            "detail": {}
        }
    ]
}`

**Anything else we need to know?**:
I am just preparing community demo for Global Azure Bootcamp. Would love to present this flow together with other ACR gems.

**Comment by yuwaMSFT2** [comment]
Thanks @mgrabarz for your comments.
This feature is not for classic registry; it's only for managed registry. The API below is ACR's v1 API, not docker API (/v2/). There is some format issue on the URL and we will fix it soon.
https://[login-url]/acr/v1/[image]/_manifests/[digest]

You call the above API to clear the quarantine state of the manifest. In order to call the API, currently you need both Contributor and AcrImageSigner roles (we are fixing a bug so after next week you can also call the API with both AcrPush and AcrImageSigner roles)

Please let us know if there is any other suggestions. You can also reach us at acrsup@microsoft.com

**Comment by mgrabarz** [comment]
Thank for help @yuwaMSFT2 , adding /acr/ to the path worked. Have no idea why I missed that!

Btw, patch request works for "quarantineState" property, but when I add "quarantineDetails" it reports error: 
`{
    "errors": [
        {
            "code": "PROPERTY_INVALID",
            "message": "the specified property or value is invalid",
            "detail": {}
        }
    ]
}`

**Comment by yuwaMSFT2** [comment]
Sorry, it should be AcrQuarantineWriter role:) I updated my previous comment.

Regarding the quarantineDetails, it's a json string with a specific schema as mentioned in the doc:
_Note: the quarantineDetails schema is defined at here_

This is the schema:
https://github.com/Azure/acr/blob/master/docs/preview/quarantine/quarantine-details/schema.json

**Comment by yuwaMSFT2** [comment]
FYI @mgrabarz this is the payload I just tried to update the details:
{
   "quarantineState": "Passed",
   "quarantineDetails": "{\"state\":\"scan passed\",\"link\":\"https://localhost\", \"scanner\":\"testscanner\", \"result\": {\"version\":\"1.1\",\"summary\":[{\"severity\":\"Low\",\"count\":10}]}}"
}

There is suggestion from users to change the json string to json for quarantineDetails so it may be changed later.

**Comment by mgrabarz** [comment]
All clear now. Thanks for the support!

Patch example from the article uses escaped string, that is why it didn't work for me.
