### ISSUE TITLE
Support for BitBucket Cloud

### ISSUE THREAD

**Issue by dreschner** [Azure/acr#238]
**What is the problem you're trying to solve**
When using task create, I have to provide a git access token. The tutorial only mentions github as example. But after some research, it looks like bitbucket server is fine too. Unfortunately, bitbucket cloud doesn't support personal access tokens (see https://community.atlassian.com/t5/Bitbucket-questions/Personal-Access-Token-for-Bitbucket-Cloud/qaq-p/677663).

**Describe the solution you'd like**
I would like to have support for bitbucket cloud by using their app password feature or OAuth.

**Additional context**
Thank you very much in advance!

**Comment by abigailbuckholdt** [comment]
I was able to connect ACR to Bitbucket cloud to create a build task using the format username:apppassword for the git access token field

**Comment by sajayantony** [comment]
@dreschner - Does @abigailbuckholdt 's solution work for you?

**Comment by gmistick** [comment]
@dreschner  , How were you able to get the Bitbucket to work?

**Comment by mallaranand** [comment]
> I was able to connect ACR to Bitbucket cloud to create a build task using the format username:apppassword for the git access token field

@abigailbuckholdt, Hi I am unable to create ACR task with bitbucket context. Since you have already achieved this. Could you please help me with the command where you were already succeded.

CLI command im using:  
az acr task create --registry <registry-name> --name task01 --image appimage:1.0 --arg <Registry-name.azurecr.io> --context "https://<username>@bitbucket.org/<workspaceid>/<Repository-name>.git" --branch <branch> --file <Dockerfile-file> --git-access-token <Oauth>

Note: I have tried with username:apppassword for the git access token field

Error is :
Operation failed with status: 'Bad Request'. Details: "{\"error\":{\"code\":\"InvalidRepositoryUrl\",\"message\":\"Invalid repository URL 'https://xxxxxxxx@bitbucket.org/xxxxxxx/xxxxxxxxx.git'. For more information see the tutorial https://aka.ms/acr/tasks/tutorial-git-trigger.\",\"target\":\"VisualStudioTeamService\",\"details\":null}}"

**Comment by northtyphoon** [comment]
@mallaranand  the above error you saw is because Tasks doesn't support commit trigger for bitbucket. You can pass `--commit-trigger-enabled false` to `az acr task create` cmd.

**Comment by northtyphoon** [comment]
@mallaranand you can also upvote @gmistick request in user voice, it will help us prioritize the feature.

https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/38705104-support-bitbucket-repositories

**Comment by mallaranand** [comment]
> @mallaranand the above error you saw is because Tasks doesn't support commit trigger for bitbucket. You can pass `--commit-trigger-enabled false` to `az acr task create` cmd.

@northtyphoon I have tried your suggestion but the same error it was showing.

**Comment by northtyphoon** [comment]
@mallaranand  I guess you used an old version of azure-cli. If so, there might be another trigger you need to turn off explicitly. Sorry for the confusion. Here are the detail steps.

1. Create an App Password in BitBucket with Repositories:Read permission.
2. Run the following command to create the task.
```
az acr task create \
 -r myregistry \
 -n mytask \
 -c https://myuser:myapppassword@bitbucket.org/myuser/myrepo.git \
 -f Dockerfile \
 --image myimage:mytag \
 --pull-request-trigger-enabled false \
 --commit-trigger-enabled false
```

3. Run the following command to manually schedule a run for the task.
```
az acr task run \
 -r myregistry
 -n mytask
```

**Comment by SteveLasker** [comment]
As a feature request, please use this UserVoice item to help rank its priority: https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/38705104-support-bitbucket-repositories

Closing this issue as it's a feature request, not an issue.
