### ISSUE TITLE
no matching manifest for unknown in the manifest list entries

### ISSUE THREAD

**Issue by LianwMS** [Azure/acr#265]
**Describe the bug**

 az acr build -image sample/buildbyacr:v1 --registry lianwacr --file Dockerfile .

The dockerfile is very simple:

FROM mcr.microsoft.com/windows/servercore@sha256:7afc10568a79ffbaf11dfc70b13937ca8bec419fb2d408499f4568f40fae3e61
COPY SSIS C:/ssis/

Can build one local machine, but when using acr build. it fails since:

Sending build context to Docker daemon  237.3MB
Step 1/2 : FROM mcr.microsoft.com/windows/servercore@sha256:7afc10568a79ffbaf11dfc70b13937ca8bec419fb2d408499f4568f40fae3e61
sha256:7afc10568a79ffbaf11dfc70b13937ca8bec419fb2d408499f4568f40fae3e61: Pulling from windows/servercore
no matching manifest for unknown in the manifest list entries
2019/08/24 09:34:30 Container failed during run: build. No retries remaining.
failed to run step ID: build: exit status 1

Questions:
1. Why? fails on cloud?
2. How to get the all support base image?

**Comment by SteveLasker** [comment]
Hi LianeMS,
Not knowing what tag you’re pulling, it’s possible the specific version isn’t yet supported or is otherwise incompatible with the host of ACR Tasks
We frequently update Tasks with the latest and greatest supported images. 
Can you use a tag reference, as opposed to manifest and let us know what windows version you’re using?
See here for more about digests and tags: 
https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/

**Comment by northtyphoon** [comment]
@lianwms, to build windows image, you need to pass ‘—platform windows’ to ‘az acr build’ command

**Comment by SteveLasker** [comment]
@steve Think horses, not zebras

**Comment by LianwMS** [comment]
@northtyphoon Thanks, I add "--platform windows" then it pass. @SteveLasker . Thanks too
