### ISSUE TITLE
Support for helm using repository scoped credentials

### ISSUE THREAD

**Issue by sam-cogan** [Azure/acr#317]
**What is the problem you're trying to solve**
At the minute it is not possible to use repository scoped permissions to push helm charts, as this requires the use of the az acr command, which as far as I know doesn't allow us to use the scoped token. This means having to grant a SP access to push the rep, which because there is not a helm only permissions, means we may as well not use the scoped permission.

**Describe the solution you'd like**
Ability to use scoped permissions to upload a helm chart

**Additional context**

**Comment by sajayantony** [comment]
The `az acr helm` command isn’t something that is going to expand and possibly reduce in usage with helm 3. The guidance and direction is to move towards helm 3 using the registry commands that work with the same set of scopes as image and hence can use the repo scoped permission tokens.

**Comment by tomkerkhove** [comment]
Will `az acr helm` be deprecated? If so, any indication when?

**Comment by sam-cogan** [comment]
so should repository scoped commands work with Helm 3 today?

**Comment by sajayantony** [comment]
There is currently no plan for deprecation. I guess the statement is more about future investments not going to helm2. /cc @SteveLasker 

@sam-cogan - this is how repo tokens works already for helm3 where I have a token for `charts\bar` and fail when pulling `charts/hello-world`

```
$ az acr token create -n bar -r sajay --repository charts/bar content/read
$ docker login -u barToken -p =$PASSWORD sajay.azurecr.io
$ export HELM_EXPERIMENTAL_OCI=1
$ helm chart pull sajay.azurecr.io/charts/bar:v1
v1: Pulling from sajay.azurecr.io/charts/bar
ref:     sajay.azurecr.io/charts/bar:v1
digest:  07ebb776cde81198df0958c5abd79eb9364249c630f41fbe04a6f0432080ea0c
size:    2.7 KiB
name:    bar
version: 0.1.0
Status: Chart is up to date for sajay.azurecr.io/charts/bar:v1
$ helm chart pull sajay.azurecr.io/charts/hello-world:v1
v1: Pulling from sajay.azurecr.io/charts/hello-world
Error: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
/cc @dlepow since you are working on the official docs for helm3.

**Comment by sam-cogan** [comment]
Yeah, just tested it and it seems to work ok. However the fact that it is currently experimental, and lack of support for dependency fetch makes it a no-go for the moment unfortunately, but makes sense that this is the way forward.

**Comment by sajayantony** [comment]
This is valuable feedback. We are working with @jdolitsky and other folks from helm to make sure this matures going forward.

**Comment by tomkerkhove** [comment]
> There is currently no plan for deprecation. I guess the statement is more about future investments not going to helm2. /cc @SteveLasker 

That makes perfect sense, thanks for clarifying @sajayantony !

**Comment by orecht** [comment]
For this information of anyone reding this issue, `az acr helm` has been depricated. See az acr release notes https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&tabs=azure-cli#july-14-2020

This breaks my build with the following error:
~~~
This command is implicitly deprecated because command group 'acr helm' is deprecated and will be removed in a future release. Use 'helm v3' instead.
{
  "saved": true
}
##[error]Script failed with error: Error: The process '/bin/bash' failed because one or more lines were written to the STDERR stream
~~~
