### ISSUE TITLE
Namespace permissions: AAD Support

### ISSUE THREAD

**Issue by mangalorereshmi** [Azure/acr#380]
https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/31655977-configure-permissions-at-a-repository-level

**Comment by SteveLasker** [comment]
[Repository scoped permissions](https://aka.ms/acr/repo-permissions) are now in public preview. However, they are limited to Tokens.

Our plan has been to add repository scoped permissions for IoT scenarios (devices in the wild) _and_ AAD based objects (services and people).

Our first priority was to enable IoT as enabling millions of devices, connecting from remote, or isolated networks was a blocker. Tokens enables near infinite scale, while limiting access to just the registry. We grouped the token feature with repo-scoped permissions.

## Additional Investigations
While adding AAD based support, we received feedback that repo scoped permissions are great, but they need to be managed by individual teams.
  [RBAC on folders/subfolders #338](https://github.com/Azure/acr/issues/338)

We're currently investigating the following design, validating with customer calls:

TeamA and TeamB both share the contoso.azurecr.io registry.
TeamA owns all the repos below:
- `contoso.azurecr.io/teama/`
  - `contoso.azurecr.io/team-a/project-1/web`
  - `contoso.azurecr.io/team-a/project-1/api`
  - `contoso.azurecr.io/team-a/project-2/web`
  - `contoso.azurecr.io/team-a/project-2/queue-processor`
TeamB owns all the repos below:
- `contoso.azurecr.io/team-b/`
  - `contoso.azurecr.io/team-b/project-3/web`
  - `contoso.azurecr.io/team-b/project-3/router`
  - `contoso.azurecr.io/team-b/project-4/web`
  - `contoso.azurecr.io/team-b/project-4/mail-processor`

Today, the owner, or contributor of the registry must assign permissions. Which means the managers of TeamA and TeamB either need to be contributors of the entire registry, or they must each ask the contributors of the entire registry to configure permissions.

We acknowledge and recognize this gap and have been doing customer calls/research to understand exactly how teams would like there shared repositories managed.
- Is it just permissions that are delegated?
- Should we isolate [audit-logs](https://aka.ms/acr/audit-logs)
- Should Webhook creation be limited to repos owned by the team?
- Should we use AAD groups to manage the teams?

While we appreciate teams are looking for repo-scoped permissions today, the impact to change is significant. Rather than release another preview, where the role names, or group management would likely change, we felt it better to gather more info before making incremental improvements that we believe would change.

## Next Steps

With many other commitments on our plate for the fall of 2020, we will spend the fall researching and validating the new design and queue up development for spring of 2021.

**Comment by SteveLasker** [comment]
For those tracking updates, I've made a few edits to identify that we've had to move this work out another 6 months.

**Comment by kn6405** [comment]
Any updates on this feature? I saw above it said development in fall of 2021 and we just reached fall. Hoping someone is working on this or will be picking it up soon. An application I'm working on now could really use this level of RBAC permissions in ACR right now. I'm really hoping for early 2022.

**Comment by PeterBennink** [comment]
Any update on this?

**Comment by davidkarlsen** [comment]
> Hi @PeterBennik,
> 
> This feature is on our roadmap. With many other commitments on our plate, we have not had a chance to prioritize this ask. Our plan here is to introduce a new resource type called Namespaces for ACR. A Namespace provides a way to group repositories within your registry. All repositories within a given namespace will share the same permissions. Example: In azurecr.io/foo/hello-world:v1 Namespace name = foo repo name = hello-world tag = v1 When available Namespaces will allow you to grant permissions to all repos within a Namespace to be accessed either by a SP, AAD user or an AAD group. Thanks, Reshmi

That sound exactly what we're after. But still there is just talk for over two years. This is a feature you'll have in ECR with AWS from day one.

**Comment by johnsonshi** [comment]
Hi @davidkarlsen,

We're working on GA'ing https://github.com/Azure/acr/issues/412 (Repository-Scoped Permissions using Tokens and Scope Maps). That feature needs to be GA'd first before the other feature first because of internal engineering dependencies.

We're aiming for a preview sometime around April to June next year (2023) for this feature (Namespace-level permissions including support for AAD).

**Comment by mosabami** [comment]
@johnsonshi  first or second half of 2023 sounds like a whole year range. can we get something more specific? :)

**Comment by johnsonshi** [comment]
Hi @mosabami, I'd say around the middle of next year would be more accurate :)

**Comment by matthew-fawcett** [comment]
Given we're at (roughly) mid 2023 is there any update as to when this may be available?

**Comment by johnsonshi** [comment]
@matthew-fawcett - We have an internal prototype integration with ABAC and are undergoing testing. At this point, it is likelier that this feature will be available for private preview on the latter half of 2023 or the first few months of 2024.

Please understand that this is a complicated Authz feature, and the Azure team needs to extensively test this so that customer's cloud native workloads are secure with this new option of authorization through ABAC permissions.

**Comment by dev-bio** [comment]
> @matthew-fawcett - We have an internal prototype integration with ABAC and are undergoing testing. At this point, it is likelier that this feature will be available for private preview on the latter half of 2023 or the first few months of 2024.
> 
> Please understand that this is a complicated Authz feature, and the Azure team needs to extensively test this so that customer's cloud native workloads are secure with this new option of authorization through ABAC permissions.

@johnsonshi Anywhere we can follow the progress on this?

**Comment by leomoreira** [comment]
> @matthew-fawcett - We have an internal prototype integration with ABAC and are undergoing testing. At this point, it is likelier that this feature will be available for private preview on the latter half of 2023 or the first few months of 2024.
> 
> Please understand that this is a complicated Authz feature, and the Azure team needs to extensively test this so that customer's cloud native workloads are secure with this new option of authorization through ABAC permissions.

Any progress with that?

**Comment by mike-miller-ct** [comment]
> > [@matthew-fawcett](https://github.com/matthew-fawcett) - We have an internal prototype integration with ABAC and are undergoing testing. At this point, it is likelier that this feature will be available for private preview on the latter half of 2023 or the first few months of 2024.
> > Please understand that this is a complicated Authz feature, and the Azure team needs to extensively test this so that customer's cloud native workloads are secure with this new option of authorization through ABAC permissions.
> 
> [@johnsonshi](https://github.com/johnsonshi) Anywhere we can follow the progress on this?

I jsut wanted to ask whether there is an update on this one? We desperately need this feature. Thank you

**Comment by johnsonshi** [comment]
Due to an unforeseen dependency, the delivery of this highly awaited feature (repository permissions through Entra ID attribute-based access control) has been delayed to the latter half of 2024.

**Comment by ebuildy** [comment]
hello @johnsonshi , sorry to ping you, at petalMD we use ACR a lot and really looking forward this feature. I have to plan a fallback to another solution because all teams push me hard for this feature, could you share a release date for Canada Central please ? thanks you so much

**Comment by jserpapinto** [comment]
Hey team, we are also using ACR and we need to segregate permissions between repositories so that we don't need an ACR per "namespace". Plz let us know the state of this.
Thanks,
Serpa

**Comment by johnsonshi** [comment]
We're excited to announce the ***Private Preview*** of ACR Repository Permissions through Attribute-Based Access Control (***ACR ABAC***). ACR ABAC for Repository Permissions is now live in all Azure production regions, enabling you to ***scope permissions to repositories during Azure Entra ID Role Assignments***.

Azure ABAC builds on Azure Entra role-based access control (Azure RBAC) by introducing the ability to set conditions when authoring Azure Entra role assignments. ABAC conditions can narrow down role assignment permissions to specific repositories within the registry based on set conditions. For example, you might ***grant access to several repositories within a namespace that start with a certain prefix***. Alternatively, you might ***grant access to a repository exactly matching a given name***. With Entra ABAC-based repository permissions, ACR now provides a more secure and controlled access management system for your cloud native workloads.

***ACR ABAC Repository Permissions*** is also compatible with Azure Entra role assignments with various Microsoft Entra ID identities, including users, groups, service principals, and managed identities. This capability is ***supported across all ACR SKUs***, ensuring a wide range of options for access management within your registry.

For more information, please see:
•	Private Preview Blog Announcement: [acr/docs/blog/abac-repo-permissions.md at main · Azure/acr (github.com)](https://github.com/Azure/acr/blob/main/docs/blog/abac-repo-permissions.md)
•	Private Preview Documentation: [acr/docs/preview/abac-repo-permissions/README.md at main · Azure/acr (github.com)](https://github.com/Azure/acr/blob/main/docs/preview/abac-repo-permissions/README.md)

**Comment by johnsonshi** [comment]
ACR's Repository Permissions is now in Private Preview and its documentation is now available at [acr/docs/preview/abac-repo-permissions/README.md at main · Azure/acr (github.com)](https://github.com/Azure/acr/blob/main/docs/preview/abac-repo-permissions/README.md).

With this feature, when you make Entra-specific role assignments, you can scope the ACR role assignments so that the identity (in the role assignee) can only read, write, and/or delete images within specific repositories. Any Entra identities, including users, groups, managed identities, and service principals, are supported for repository permissions scoping with ACR ABAC.

This is a significant step in ACR's security and permissions model as it allows multiple teams to host images within a single ACR (and segregate permissions).

For further questions, please contact **acr-abac-preview@microsoft.com**, which is externally reachable.

Note: Public Preview details and timelines are still being determined.

**Comment by hterik** [comment]
> For further questions, please contact **[acr-abac-preview@microsoft.com](mailto:acr-abac-preview@microsoft.com)**, which is externally reachable.

This still bounces with a reply from postmaster@microsoft.com saying 

> The group acr-pm only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

**Comment by johnsonshi** [comment]
For further questions about Entra ID-based ACR Repository Permissions, please contact [acr-abac-preview@microsoft.com](mailto:acr-abac-preview@microsoft.com), which is externally reachable. We've been receiving multiple such external requests and the email is indeed externally reachable. Thank you!

**Comment by audunsolemdal** [comment]
Good news

https://learn.microsoft.com/en-us/azure/container-registry/container-registry-rbac-abac-repository-permissions?tabs=azure-portal

**Comment by johnsonshi** [comment]
This is now GA.
