### ISSUE TITLE
cannot pull a singularity container

### ISSUE THREAD

**Issue by fertinaz** [Azure/acr#411]
**Describe the bug**
Trying to pull a singularity container that I pushed to ACR. It fails with the following error:
```
Code: ContainerInvalidImage

Message:
One or more container images specified are invalid

Values:
ContainerImage - fertinazopenfoam.azurecr.io/openfoam-7:latest
Message - unexpected end of JSON input
```

**I can successfully pull and run a sample command using a Docker container image.**

**To Reproduce**
This is how I pushed my container image:
```
singularity push --docker-username ${USERNAME} --docker-password ${PASSWORD} \
  $HOME/singularity-images/of-7.sif oras://fertinazopenfoam.azurecr.io/openfoam-7:latest
```

I'm using azure batch (c# sdk) to pull the container. Code below is the part where I define ACR related stuff:
```
            var c = new Container(containerHub, myJob.Software);
            string imageName = c.Image;

            var containerRegistry = new ContainerRegistry(c.Username,
                            c.RegistryServer,
                            c.Password);

            var containerConfiguration = new ContainerConfiguration
            {
                ContainerImageNames = new List<string> { imageName },
                ContainerRegistries = new List<ContainerRegistry> { containerRegistry }
            };

            vmConfiguration.ContainerConfiguration = containerConfiguration;

            CreateBatchPool(batchClient, vmConfiguration, PoolName, myJob.Nodes);
```

**Any relevant environment information**
 - OS: ```
                publisher: "microsoft-azure-batch",
                offer: "ubuntu-server-container",
                sku: "16-04-lts",
                version: "latest");
           ```
 - netcoreapp3.1

**Additional context**
Please let me know if you need additional details.

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by SteveLasker** [comment]
@sajayantony ?

**Comment by shizhMSFT** [comment]
It seems that [Azure Batch libraries for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/batch?view=azure-dotnet) only supports Docker images. Therefore, it treats the singularity image with the protocol `oras://` as a docker image. As a result, it fails with `unexpected end of JSON input`, which is expected since singularity images cannot be pulled using `docker pull`.
```
$ docker pull ${name}.azurecr.io/singularity/hello-world:latest
latest: Pulling from singularity/hello-world
4eb5ef00fff3: Pulling fs layer
unexpected end of JSON input
```
Nonetheless, singularity images / containers are supported by Azure Batch via [Azure Batch Shipyard](https://github.com/Azure/batch-shipyard). [Documentations](https://batch-shipyard.readthedocs.io/en/latest/11-batch-shipyard-configuration-credentials/#docker-and-singularity-registries-docker_registry-and-singularity_registry) are available for pulling singularity images from Azure Container Registry.

@fertinaz For further information about Azure Batch, please open issues in [Azure/Batch](https://github.com/Azure/batch/issues) GitHub repository for better support can tracking.

**Comment by shizhMSFT** [comment]
In addition, singularity images are incompatible with native container support enabled pools. In other words, singularity images are incompathible with the offer `ubuntu-server-container` by the publisher `microsoft-azure-batch`.

**Comment by vermagit** [comment]
@alfpark Would it be fair to say that support for Singularity does not yet extend beyond Batch Shipyard to native Batch and SDK?

**Comment by fertinaz** [comment]
Hello, thanks for the info. I appreciate that. 

I know about `batch-shipyard`, used it in the past and even contacted @alfpark about some details because I was a part of the UberCloud team. You guys might know about them.

I'm a bit surprised to hear that "Azure Batch libraries for .NET only supports Docker images". Somehow, I was assuming that `batch-shipyard` uses Python SDK for Batch. Should I open an issue in Batch repo for potential workarounds?

**Comment by vermagit** [comment]
@fertinaz Yes of course, UberCloud is a key partner.
IIRC, they use docker containers to package the apps and they have it working well with RDMA etc.
@alfpark is the SME here, though I would also suggest opening an issue in the Batch repo so that team is aware of this request.

**Comment by shizhMSFT** [comment]
This ACR-side issue is closed as it is tracked from the Azure Batch side.
