### ISSUE TITLE
How to use ACR in AKS from different tenant

### ISSUE THREAD

**Issue by shreelola** [Azure/acr#427]
Hi,
I have ACR running on tenant A, I would like to attach ACR from  tenant A to Tenant B and Tenant C AKS clusters. I would like to do passwordless image pull on  Tenant B and Tenant C AKS clusters and manage account settings on AAD level.

**Comment by hkuadithya** [comment]
@shreelola I'm not entirely sure if that's possible since this comes under AAD.
Are you the owner of the subscription which contains ACR from TenantA?

Can you try this and report the errors (if any)?
```
az aks create -n <AKS_from_TenantB> -g <ResourceGroup> --generate-ssh-keys --attach-acr <acr_resource_id_from_TenantA>
```

**Comment by northtyphoon** [comment]
@shreelola you set up the AKS using a service principal. It can be used as default credential to pull images from ACR. Does it match "your passwordless image pull" expectation? If yes, there is a way to enable the app backing the service principal to multi-tenant so that it can pull images from ACR in different tenants.

**Comment by shreelola** [comment]
@hkuadithya command fails to create a role assignment.
`Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?`

@northtyphoon Yes, I can set up a AKS using a service principal on Tenant B and C. How can I update AKS to use ACR from Tenant A?

**Comment by northtyphoon** [comment]
@shreelola, the workflow is opposite. 

1. First go to the AAD App (Azure Portal) for the service principal you used to create AKS, enable multi-tenant on the App,

![image](https://user-images.githubusercontent.com/2686301/88866822-a62b4100-d1c0-11ea-91ff-5ee35debc9dd.png)

2. Create the service principal in Tenant B and C using the above multi-tenant app. Internally, we have to follow a process to do it. I don't know how to do it through portal.  You may need to file a support ticket to Azure AAD team to request it. 

3. After you create each service principal in Tenant B and C, you can go to ACR ACL and grant ACRPull role to the corresponding service principal. 

4. You can now pull image in AKS (Tenant A) from ACR (Tenant B or C)

**Comment by northtyphoon** [comment]
@shreelola did you get a chance to try?

**Comment by shreelola** [comment]
@northtyphoon Thanks for the step by step explanation,  I couldn't follow step-2 with azure cli command, nor from the Portal.
I was trying to figure out cli command to create sp: https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest
Can you please guide here? We want to do the complete steps programatically. It would be difficult to raise Azure support ticket each time when we add the new account.  ACR is running on our tenant and AKS will be running on customers tenant. 
Can you please help me on Step2.

**Comment by lualvare** [comment]
Hello @northtyphoon, 

I am having the same exact concern here **"I would like to attach ACR from tenant A to Tenant B and Tenant C AKS clusters."**,  Could you please elaborate more on the steps given on you udpate https://github.com/Azure/acr/issues/427#issuecomment-666007698 ?

Thank you so much, I appreciate it in advanced.

Luis Alvarez.

**Comment by northtyphoon** [comment]
@shreelola @lualvare I don't know how to do step-2 programmatically. We internally also need to file a ticket to Azure Active Directory team to do it. May I suggest you file a ticket to Azure Active Directory for assistance?

Alternatively, you may consider to create a token for each of your customers. They can use the token as ImagePullSecrets in AKS to pull images from your ACR.
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions

**Comment by assafbari** [comment]
@shreelola, I've encountered the same issue.
I was able to solve it by creating a multi-tenant SPN in **tenant B** and grant it with the permission of ACRPull over **tenant A** ACR as @northtyphoon suggested. 

There is one important missing step in the above solution in order to make it works:
You need to give **Tenant A** access to the multi-tenant SPN by requesting a sign-in using a browser as described under _[Give Tenant 2 access](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/share-images-across-tenants#give-tenant-2-access)_ section in the documentation of the Azure Shared Image Gallery.

I believe Microsoft should add the relevant documentation for ACR as well, as this is probably a common use case not just for Shared Image Gallery.
