### ISSUE TITLE
Deleting tag does not delete layers that aren't used by other images

### ISSUE THREAD

**Issue by bbgobie** [Azure/acr#519]
**Describe the bug**
Deleting specific images does not delete layers associated with the image even if they are not used by any other image.

**To Reproduce**
1. Build a unique Dockerfile and push it.
`FROM alpine
RUN echo foo > file`
`docker build . -t <registry>/repo:tag`
2. Push the image
`docker push registry/repo:tag`
3. Delete that specific image.
`az acr repository delete --name <registry> --image repo:tag`
4.  Push the image again
You will see something like this, where 2 layers already exist
`d8db02adccbd: Layer already exists 
cb381a32b229: Layer already exists
v1: digest: sha256:1617669d3ff4ee22fb3b166e85a922a10515eae53214761b4ae76eafef1601de size: 735`
**Expected behavior**
Following the above example, 1 or 2 new layers should be pushed on the 2nd push.  At least 1 because presumably you wouldn't have an image that used the 2nd layer in the image you deleted.  2 if you happen to not have the alpine.

**Screenshots**

**Any relevant environment information**
This happens whether I use:

-  az acr repository delete
- run an acr purge command
- delete from web console

**Additional context**
I believe this causes layers to be stored which we will have no way to purge without deleting the entire repository adding up on storage costs.

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by kevin-tong-msft** [comment]
It is not a bug. Two concepts to clarify when you delete a manifest (image)

**layer blob cleanup**
It could take up to 7 days for background service to clean up any layer with zero reference count (i.e., layer not being used by any other images). That's why you may see "Layer already exists .." when you push the same image again. 
Note: ACR maintains some internal data structures so "layer blob cleanup" may not be accurate but you can understand in this way.

**billing**
When you delete an image, any layer not used by other images would be unmarked for billing. It will NOT be counted towards storage use for billing purpose, even if the layer hasn't been cleaned up yet.

In sum, layer cleanup and storage usage count are independent. You would not be charged for layers due to be cleaned up.

You may convince yourself by following test:

1. Create a basic plan ACR.
2. Push a large image (only one image for simplicity), e.g. of 500MB size.
3. Wait for the billing service to update the usage in portal (could up to a day). Confirm usage is 0.5GB
4. Delete the manifests.
5. Wait for the billing service to update the usage in portal. Confirm usage is 0GB.
