### ISSUE TITLE
Retention policy deletes retagged images

### ISSUE THREAD

**Issue by mkstephenson** [Azure/acr#520]
**Describe the bug**
With the retention policy enabled, any manifests which are completely untagged and then re-tagged are still deleted, resulting in the case that images are still listed in the registry but the underlying manifest is no longer available.

**To Reproduce**
1. Enable the retention policy on the registry
2. Upload an image to the registry with one tag
2. Delete that tag
3. Shortly afterwards (maybe an hour or two, I retagged them the following day) add the tag again to the image again.
4. Wait for the retention policy time to elapse
5. Verify that the tag and repositoriy is visible in the Azure portal but the manifest is missing

**Expected behavior**
As soon as a tag is added to a manifest again, I expect that the delayed task which deletes the manifest and layers to be cancelled and the image should still be available after the elapsed retention policy time.

**Comment by ankurkhemani** [comment]
@mkstephenson Do you have an ACR with geo-replication enabled? We are looking into this, will provide an update soon.

**Comment by mkstephenson** [comment]
Currently no, this is not being replicated anywhere

**Comment by ankurkhemani** [comment]
@mkstephenson We have identified this as a bug on our end due to a change that can prevent invalidating the purge after the retag. Our team will work on a fix and rollout asap. 

For now, we recommend disabling the policy until the fix is rolled out. Please let us know if there's a particular image you need recovered. Or, you can simply push the image again after disabling the policy (and final retention purge) if that's an option. sorry for the inconvenience.

**Comment by mkstephenson** [comment]
@ankurkhemani thanks, we currently don't have any which need recovering. Over which channels you be announcing that the bugfix has been rolled out?

**Comment by ankurkhemani** [comment]
@mkstephenson We will provide you an update here.

**Comment by yugangw-msft** [comment]
Fix was rolled out
