### ISSUE TITLE
Monitoring of geo-replication progress of ACR images

### ISSUE THREAD

**Issue by xuto2** [Azure/acr#575]
**What is the problem you're trying to solve**
We recently enabled the geo-replication for our ACR registry, but we found no way in Azure Monitor to automatically monitor/query the replication status of a particular image. The webhook provided by ACR can be used for notifications to third party but not Azure monitor itself.

**Describe the solution you'd like**
I'd like to see an entry for each geo-replication events in the ContainerRegistryRepositoryEvents so we can easily tell if/when the image is replicated to a specific region.

**Additional context**
n/a

**Comment by xuto2** [comment]
Or, is there any other third party service(such as SignalFX) that would provide this level of monitoring?

**Comment by vivekunni** [comment]
Yes, even we have a geo-replication registry but don't find a placeholder to monitor the replication status in Azure portal.

**Comment by iamjasonp** [comment]
Hi folks - thank you for the feature request! 

At the moment we don't expose replication status of any individual image; indeed, it's not particularly easy to figure out the state of replication the registry. As such, I've put the feature request to make it easier to find out replication status into our feature backlog for triage and prioritization

.

For reference - for new replications, should you wish to monitor replication status (of the registry rather than a particular image) manually, it's possible to do this via the Portal. 

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-geo-replication

> Once complete, the portal reflects Ready. The replica status in the portal doesn't automatically update. Use the refresh button to see the updated status.

Thanks!

**Comment by Mint-6263** [comment]
:blush:

**Comment by xuto2** [comment]
Thanks @iamjasonp ! A similar question - what is the recommended way to monitor which replicate of image is serving the image pull request?
