### ISSUE TITLE
Failing pulls from an ACS Kubernetes Cluster

### ISSUE THREAD

**Issue by DonMartin76** [Azure/acr#72]
Since a couple of days, we have had sporadical pull failures from our Azure Container Registry (classic) hosted in Europe West from our Kubernetes 1.8.2 cluster we created with `acs-engine` tooling.

When running a `kubectl describe pod`, we just see that the cluster is pulling the image, but that it's apparently very slow. Our pipelines cancel the rollout after ten minutes, if the container is not yet up then, as pulling one of our images usually doesn't take more than 1-2 minutes (maximum).

Our container registry has around 180-190 GB of images, and it's been around a while, so it's obviously still a "classic" unmanaged registry. Are you aware of any kind of rate limiting which might kick in? Is there something we can do about it, and/or debug/error trace to see why this happens?

I just triggered an upgrade to a "managed registry", where we'd obviously be willing to pay the "Premium" tier (which is very fairly priced at around 50€ a month, good work!), and hope it gets better with this. How good are chances it will help?

**Comment by sajayantony** [comment]
The [rates limits](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-skus) are to avoid abuse of the system in most cases. If the rates you get on Premium tier aren't good enough, please let us know. 
The other benefit you will be seeing since you migrated is that your images will be replicated, which gives you better docker pull performance for Premium and we also will be rolling out a faster metadata API over the managed registry. 

We do have the requirement of showing registry telemetry in our backlog.
If you want us to investigate further regarding your pull failure, please send your registry information to acrfeedback@microsoft.com

**Comment by sajayantony** [comment]
Closing this for now. Feel free to reopen if you see this happening again.

**Comment by DonMartin76** [comment]
Yes, sorry, all is good with the premium tiered ACR. Hasn't happened since. I guess we were over the specs of the preview tier.
